name: yolo
description: My Flutter Application for Real Time Object Detection / Semantic Segmentation.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

# DEPENDENSIS
dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5
  flutter_vision: ^1.1.4
  permission_handler: ^11.0.1
  flutter_tts: ^4.0.2

  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.0.5

# DEV DEPENDENSIS
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

# INISIATI FOLDER ASET
flutter:
  assets:
    - assets/
  uses-material-design: true

# UNTUK MERUBAH IKON LAUNCHER
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/indah_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
